const AxonShop = (() => {
  const STORAGE = 'axon-store-v1';
  const starterFront = 'WhatsApp%20Image%202026-08-30%20at%2012.00.40%20PM.jpeg';
  const starterBack = 'WhatsApp%20Image%202026-08-30%20at%2012.00.40%20PM%20(1).jpeg';
  const defaults = { visits: 0, categories: ['All', 'Gym shirt', 'Oversized'], products: [{ id: 'core-tee', name: 'Core performance tee', category: 'Gym shirt', price: 89, quantity: 24, description: 'A close-to-body performance layer with a clean Axon mark. Built for heavy sessions and everyday movement.', front: starterFront, back: starterBack, variants: [] }] };
  const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  const imageData = (file) => new Promise((resolve) => { if (!file) return resolve(''); const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(file); });
  const oldStore = () => { try { return JSON.parse(localStorage.getItem(STORAGE)); } catch { return null; } };
  const normalize = (store) => ({ ...store, products: (store.products || []).map((product) => ({ ...product, variants: Array.isArray(product.variants) ? product.variants : [], sizes: Array.isArray(product.sizes) ? product.sizes : [] })) });
  async function getStore() { const response = await fetch('/api/store'); const payload = await response.json(); if (!payload.initialized) { const local = oldStore(); if (local) { const migrated = normalize(local); await saveStore(migrated); return migrated; } } return normalize(payload.store || defaults); }
  async function saveStore(store) { await fetch('/api/store', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ store }) }); localStorage.setItem(STORAGE, JSON.stringify(store)); }
  const whatsappUrl = (product, color = '') => `https://wa.me/96176419472?text=${encodeURIComponent(`Hi Axon, I would like to order the ${product.name}${color ? ` in ${color}` : ''}.`)}`;
  const colorMarkup = (product) => (product.variants || []).length ? `<div class="color-dots" aria-label="Available colors">${product.variants.map((variant) => `<span class="color-dot" style="--swatch:${esc(variant.hex)}" title="${esc(variant.name)}"></span>`).join('')}</div>` : '';

  async function initShop() {
    let store = await getStore(); await fetch('/api/visit', { method: 'POST' });
    const grid = document.getElementById('productGrid'); const tabs = document.getElementById('categoryTabs'); const search = document.getElementById('productSearch'); const empty = document.getElementById('emptyState'); let activeCategory = 'All';
    const renderTabs = () => { tabs.innerHTML = store.categories.map((category) => `<button class="category-tab ${category === activeCategory ? 'active' : ''}" data-category="${esc(category)}">${esc(category)}</button>`).join(''); tabs.querySelectorAll('button').forEach((button) => button.addEventListener('click', () => { activeCategory = button.dataset.category; renderTabs(); renderProducts(); })); };
    const renderProducts = () => { const query = search.value.trim().toLowerCase(); const products = store.products.filter((product) => (activeCategory === 'All' || product.category === activeCategory) && `${product.name} ${product.category}`.toLowerCase().includes(query)); empty.classList.toggle('hidden', products.length > 0); grid.innerHTML = products.map((product) => `<article class="product-card"><div class="product-image"><img src="${product.front}" alt="${esc(product.name)}"><span class="stock-badge ${product.quantity < 1 ? 'sold' : ''}">${product.quantity < 1 ? 'Sold out' : `${product.quantity} in stock`}</span><button class="product-quick" data-product="${product.id}">View piece ↗</button></div><div class="product-details"><p class="eyebrow">${esc(product.category)}</p><h3>${esc(product.name)}</h3>${colorMarkup(product)}<div class="product-bottom"><span class="product-price">$${esc(product.price)}</span><a class="product-wa" href="${whatsappUrl(product)}" target="_blank" rel="noreferrer">WhatsApp ↗</a></div></div></article>`).join(''); grid.querySelectorAll('.product-quick').forEach((button) => button.addEventListener('click', () => openProduct(store.products.find((product) => product.id === button.dataset.product)))); };
    const modal = document.getElementById('productModal'); const modalImage = document.getElementById('modalImage'); const viewTag = document.getElementById('viewTag'); const swatches = document.getElementById('colorSwatches'); const picker = document.getElementById('colorPicker'); const selectedColor = document.getElementById('selectedColor'); const sizePicker = document.getElementById('sizePicker'); const sizeSwatches = document.getElementById('sizeSwatches'); let currentProduct; let currentView = 'front'; let activeVariant;
    function openProduct(product) { if (!product) return; currentProduct = product; activeVariant = product.variants?.[0]; currentView = 'front'; document.getElementById('modalCategory').textContent = product.category; document.getElementById('modalName').textContent = product.name; document.getElementById('modalDescription').textContent = product.description || 'Built for your next session.'; document.getElementById('modalPrice').textContent = `$${product.price}`; document.getElementById('modalStock').textContent = product.quantity > 0 ? `${product.quantity} available` : 'Currently sold out'; picker.classList.toggle('hidden', !product.variants?.length); sizePicker.classList.toggle('hidden', !product.sizes?.length); sizeSwatches.innerHTML = (product.sizes || []).map((size) => `<span class="size-swatch">${esc(size)}</span>`).join(''); swatches.innerHTML = (product.variants || []).map((variant, index) => `<button class="modal-swatch ${index === 0 ? 'active' : ''}" data-variant="${index}" style="--swatch:${esc(variant.hex)}" aria-label="${esc(variant.name)}"></button>`).join(''); selectedColor.textContent = activeVariant ? activeVariant.name : ''; swatches.querySelectorAll('button').forEach((button) => button.addEventListener('click', () => { activeVariant = currentProduct.variants[Number(button.dataset.variant)]; selectedColor.textContent = activeVariant.name; setView(); })); setView(); modal.classList.remove('hidden'); }
    function setView() { const image = currentView === 'front' && activeVariant?.image ? activeVariant.image : (currentView === 'back' && currentProduct.back ? currentProduct.back : currentProduct.front); modalImage.src = image; modalImage.alt = `${currentProduct.name} ${activeVariant?.name || ''} ${currentView}`; viewTag.textContent = currentView.toUpperCase(); document.getElementById('modalWhatsapp').href = whatsappUrl(currentProduct, activeVariant?.name); document.querySelectorAll('.viewer-button').forEach((button) => button.classList.toggle('active', button.dataset.view === currentView)); document.querySelectorAll('.modal-swatch').forEach((button) => button.classList.toggle('active', currentProduct.variants?.[Number(button.dataset.variant)] === activeVariant)); }
    document.getElementById('modalClose').addEventListener('click', () => modal.classList.add('hidden')); modal.addEventListener('click', (event) => { if (event.target === modal) modal.classList.add('hidden'); }); document.querySelectorAll('.viewer-button').forEach((button) => button.addEventListener('click', () => { currentView = button.dataset.view; setView(); })); search.addEventListener('input', renderProducts); renderTabs(); renderProducts(); setInterval(async () => { const latest = await getStore(); if (JSON.stringify(latest) !== JSON.stringify(store)) { store = latest; renderTabs(); renderProducts(); } }, 5000);
  }

  async function initAdmin() {
    let store = await getStore(); const list = document.getElementById('adminProductList'); const categoryList = document.getElementById('categoryList'); const modal = document.getElementById('productFormModal'); const toast = document.getElementById('toast'); const colorList = document.getElementById('colorVariantList');
    const refresh = () => { document.getElementById('visitCount').textContent = store.visits; document.getElementById('productCount').textContent = store.products.length; document.getElementById('categoryCount').textContent = Math.max(0, store.categories.length - 1); list.innerHTML = store.products.map((product) => `<div class="admin-product-row"><img class="admin-product-thumb" src="${product.front}" alt=""><div><h3>${esc(product.name)}</h3><p>${esc(product.category)} · $${product.price} · ${product.quantity} units${product.variants?.length ? ` · ${product.variants.length} colors` : ''}</p></div><div class="admin-actions"><strong>${product.quantity > 0 ? 'Live' : 'Sold out'}</strong><button class="delete-button" data-delete="${product.id}">Remove</button></div></div>`).join(''); categoryList.innerHTML = store.categories.filter((category) => category !== 'All').map((category) => `<div class="category-row"><span>${esc(category)}</span><button data-category-delete="${esc(category)}" aria-label="Remove ${esc(category)}">×</button></div>`).join(''); list.querySelectorAll('[data-delete]').forEach((button) => button.addEventListener('click', async () => { store.products = store.products.filter((product) => product.id !== button.dataset.delete); await saveStore(store); refresh(); showToast('Product removed'); })); categoryList.querySelectorAll('[data-category-delete]').forEach((button) => button.addEventListener('click', async () => { if (store.products.some((product) => product.category === button.dataset.categoryDelete)) return showToast('Move products out of this category first'); store.categories = store.categories.filter((category) => category !== button.dataset.categoryDelete); await saveStore(store); refresh(); showToast('Category removed'); })); };
    const showToast = (message) => { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2200); };
    const setPreview = (inputId, previewId) => document.getElementById(inputId).addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { document.getElementById(previewId).innerHTML = `<img src="${reader.result}" alt="">`; }; reader.readAsDataURL(file); });
    const addColorRow = () => { const row = document.createElement('div'); row.className = 'color-variant-row'; row.innerHTML = `<input class="color-name" required maxlength="20" placeholder="Color name"><input class="color-hex" type="color" value="#222222" title="Choose swatch color"><label class="color-image-input"><span>＋ Photo</span><input class="color-image" type="file" accept="image/*"></label><button class="remove-color" type="button" aria-label="Remove color">×</button>`; colorList.appendChild(row); row.querySelector('.color-image').addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { row.querySelector('.color-image-input span').innerHTML = `<img src="${reader.result}" alt="">`; }; reader.readAsDataURL(file); }); row.querySelector('.remove-color').addEventListener('click', () => row.remove()); };
    const openForm = () => { const select = document.getElementById('productCategory'); select.innerHTML = store.categories.filter((category) => category !== 'All').map((category) => `<option>${esc(category)}</option>`).join(''); colorList.innerHTML = ''; addColorRow(); modal.classList.remove('hidden'); };
    document.getElementById('showAddProduct').addEventListener('click', openForm); document.getElementById('addColor').addEventListener('click', addColorRow); document.getElementById('formClose').addEventListener('click', () => modal.classList.add('hidden')); modal.addEventListener('click', (event) => { if (event.target === modal) modal.classList.add('hidden'); }); setPreview('frontImage', 'frontPreview'); setPreview('backImage', 'backPreview');
    document.getElementById('categoryForm').addEventListener('submit', async (event) => { event.preventDefault(); const input = document.getElementById('newCategory'); const value = input.value.trim(); if (!value || store.categories.includes(value)) return; store.categories.push(value); await saveStore(store); input.value = ''; refresh(); showToast('Category added'); });
    document.getElementById('productForm').addEventListener('submit', async (event) => { event.preventDefault(); const front = await imageData(document.getElementById('frontImage').files[0]); const back = await imageData(document.getElementById('backImage').files[0]); if (!front) return showToast('Choose a front image first'); const variants = await Promise.all([...colorList.querySelectorAll('.color-variant-row')].map(async (row) => ({ name: row.querySelector('.color-name').value.trim(), hex: row.querySelector('.color-hex').value, image: await imageData(row.querySelector('.color-image').files[0]) }))); const sizes = [...document.querySelectorAll('input[name="productSize"]:checked')].map((input) => input.value); store.products.unshift({ id: `product-${Date.now()}`, name: document.getElementById('productName').value.trim(), category: document.getElementById('productCategory').value, price: Number(document.getElementById('productPrice').value), quantity: Number(document.getElementById('productQuantity').value), description: document.getElementById('productDescription').value.trim(), front, back: back || front, variants: variants.filter((variant) => variant.name && variant.image), sizes }); await saveStore(store); event.target.reset(); colorList.innerHTML = ''; document.getElementById('frontPreview').textContent = '＋'; document.getElementById('backPreview').textContent = '＋'; modal.classList.add('hidden'); refresh(); showToast('Product published'); }); refresh(); setInterval(async () => { const latest = await getStore(); if (JSON.stringify(latest) !== JSON.stringify(store)) { store = latest; refresh(); } }, 5000);
  }
  return { initShop, initAdmin };
})();
