const http = require('http');
const fs = require('fs');
const path = require('path');
const { DatabaseSync } = require('node:sqlite');

const PORT = Number(process.env.PORT) || 4173;
const ROOT = __dirname;
const DB_FILE = path.join(ROOT, 'axon.db');
const LEGACY_STORE = path.join(ROOT, 'store.json');
const SUPABASE_URL = (process.env.SUPABASE_URL || '').replace(/\/rest\/v1\/?$/, '');
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const SUPABASE_ENABLED = Boolean(SUPABASE_URL && SUPABASE_SERVICE_ROLE_KEY && !SUPABASE_URL.includes('your-project'));
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.jpeg': 'image/jpeg', '.jpg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp' };
const starterFront = 'WhatsApp%20Image%202026-08-30%20at%2012.00.40%20PM.jpeg';
const starterBack = 'WhatsApp%20Image%202026-08-30%20at%2012.00.40%20PM%20(1).jpeg';
const defaults = { visits: 0, categories: ['All', 'Gym shirt', 'Oversized'], products: [{ id: 'core-tee', name: 'Core performance tee', category: 'Gym shirt', price: 89, quantity: 24, description: 'A close-to-body performance layer with a clean Axon mark. Built for heavy sessions and everyday movement.', front: starterFront, back: starterBack, variants: [] }] };
const db = new DatabaseSync(DB_FILE);
db.exec('PRAGMA journal_mode = WAL; CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS categories (name TEXT PRIMARY KEY); CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, price REAL NOT NULL, quantity INTEGER NOT NULL, description TEXT, front TEXT NOT NULL, back TEXT, variants TEXT NOT NULL);');

function normalize(store) { return { ...store, products: (store.products || []).map((product) => ({ ...product, variants: Array.isArray(product.variants) ? product.variants : [] })) }; }
function loadStore() { const count = db.prepare('SELECT COUNT(*) AS count FROM categories').get().count; if (!count) { let imported = defaults; if (fs.existsSync(LEGACY_STORE)) { try { imported = normalize(JSON.parse(fs.readFileSync(LEGACY_STORE, 'utf8'))); } catch {} } saveStore(imported); } const visits = Number(db.prepare('SELECT value FROM settings WHERE key = ?').get('visits')?.value || 0); const categories = db.prepare('SELECT name FROM categories ORDER BY rowid').all().map((row) => row.name); const products = db.prepare('SELECT * FROM products ORDER BY rowid DESC').all().map((row) => ({ id: row.id, name: row.name, category: row.category, price: row.price, quantity: row.quantity, description: row.description || '', front: row.front, back: row.back || row.front, variants: JSON.parse(row.variants || '[]') })); return { visits, categories, products }; }
async function supabaseRequest(endpoint, options = {}) { const response = await fetch(`${SUPABASE_URL}/rest/v1/${endpoint}`, { ...options, headers: { apikey: SUPABASE_SERVICE_ROLE_KEY, Authorization: `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); if (!response.ok) throw new Error(`Supabase ${response.status}: ${await response.text()}`); return response.status === 204 ? null : response.json(); }
async function loadSharedStore() { if (!SUPABASE_ENABLED) return loadStore(); const rows = await supabaseRequest('axon_store?id=eq.main&select=payload'); if (rows.length) return normalize(rows[0].payload); const local = loadStore(); await saveSharedStore(local); return local; }
async function saveSharedStore(store) { if (SUPABASE_ENABLED) { await supabaseRequest('axon_store', { method: 'POST', headers: { Prefer: 'resolution=merge-duplicates,return=minimal' }, body: JSON.stringify({ id: 'main', payload: normalize(store), updated_at: new Date().toISOString() }) }); return; } saveStore(store); }
function saveStore(store) { const normalized = normalize(store); db.exec('BEGIN'); try { db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run('visits', String(normalized.visits || 0)); db.exec('DELETE FROM categories; DELETE FROM products'); const addCategory = db.prepare('INSERT INTO categories(name) VALUES(?)'); normalized.categories.forEach((category) => addCategory.run(category)); const addProduct = db.prepare('INSERT INTO products(id,name,category,price,quantity,description,front,back,variants) VALUES(?,?,?,?,?,?,?,?,?)'); normalized.products.forEach((product) => addProduct.run(product.id, product.name, product.category, Number(product.price), Number(product.quantity), product.description || '', product.front, product.back || product.front, JSON.stringify(product.variants || []))); db.exec('COMMIT'); } catch (error) { db.exec('ROLLBACK'); throw error; } }
function sendJson(res, status, data) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(data)); }
function readBody(req) { return new Promise((resolve, reject) => { let body = ''; req.on('data', (chunk) => { body += chunk; if (body.length > 25 * 1024 * 1024) reject(new Error('Request too large')); }); req.on('end', () => { try { resolve(JSON.parse(body || '{}')); } catch { reject(new Error('Invalid JSON')); } }); req.on('error', reject); }); }
function serveFile(req, res) { const requested = decodeURIComponent(req.url === '/' ? '/shop.html' : req.url); const file = path.resolve(ROOT, `.${requested}`); if (!file.startsWith(ROOT) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return sendJson(res, 404, { error: 'Not found' }); res.writeHead(200, { 'Content-Type': MIME[path.extname(file).toLowerCase()] || 'application/octet-stream' }); fs.createReadStream(file).pipe(res); }

const server = http.createServer(async (req, res) => { try { if (req.url === '/api/store' && req.method === 'GET') return sendJson(res, 200, { initialized: true, backend: SUPABASE_ENABLED ? 'supabase' : 'sqlite', store: await loadSharedStore() }); if (req.url === '/api/store' && req.method === 'PUT') { const payload = await readBody(req); if (!payload.store || !Array.isArray(payload.store.products) || !Array.isArray(payload.store.categories)) return sendJson(res, 400, { error: 'Invalid store' }); await saveSharedStore(payload.store); return sendJson(res, 200, { store: await loadSharedStore() }); } if (req.url === '/api/visit' && req.method === 'POST') { const store = await loadSharedStore(); store.visits += 1; await saveSharedStore(store); return sendJson(res, 200, { visits: store.visits }); } return serveFile(req, res); } catch (error) { sendJson(res, 500, { error: error.message }); } });
server.listen(PORT, '0.0.0.0', () => console.log(`AXON ${SUPABASE_ENABLED ? 'Supabase' : 'SQLite'} server running at http://localhost:${PORT}`));
